// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--lldndxvmY1jCmgfGjv5zbXrOzB6ilg',
    appId: '1:359092957844:web:c2e32f662d646c433dba81',
    messagingSenderId: '359092957844',
    projectId: 'wa-flutter-fire-chat-app',
    authDomain: 'wa-flutter-fire-chat-app.firebaseapp.com',
    storageBucket: 'wa-flutter-fire-chat-app.appspot.com',
    measurementId: 'G-SZCRVGLD75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt9mKXi0JqObfs0JrD0jFYbgnV78vqS98',
    appId: '1:359092957844:android:bc41e4f9b200a41d3dba81',
    messagingSenderId: '359092957844',
    projectId: 'wa-flutter-fire-chat-app',
    storageBucket: 'wa-flutter-fire-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyIHzDYXQEYNm5NJ9yLWwic1JDe491UY',
    appId: '1:359092957844:ios:e89c9005b8d2a53a3dba81',
    messagingSenderId: '359092957844',
    projectId: 'wa-flutter-fire-chat-app',
    storageBucket: 'wa-flutter-fire-chat-app.appspot.com',
    iosBundleId: 'com.example.flutterFireChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqyIHzDYXQEYNm5NJ9yLWwic1JDe491UY',
    appId: '1:359092957844:ios:e89c9005b8d2a53a3dba81',
    messagingSenderId: '359092957844',
    projectId: 'wa-flutter-fire-chat-app',
    storageBucket: 'wa-flutter-fire-chat-app.appspot.com',
    iosBundleId: 'com.example.flutterFireChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA--lldndxvmY1jCmgfGjv5zbXrOzB6ilg',
    appId: '1:359092957844:web:66ff219d62602d6c3dba81',
    messagingSenderId: '359092957844',
    projectId: 'wa-flutter-fire-chat-app',
    authDomain: 'wa-flutter-fire-chat-app.firebaseapp.com',
    storageBucket: 'wa-flutter-fire-chat-app.appspot.com',
    measurementId: 'G-J8JMN4NN7J',
  );

}